# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r pip-sample/requirements.txt
  displayName: 'Install dependencies'

- script: |
    npm install
    displayName: 'npm install'
- script: |
    sudo npm install -g snyk
    # create variable in Pipelines called 'SNYK_TOKEN' and securely save your Snyk token value
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
    sudo snyk auth $(SNYK_TOKEN)
    displayName: 'install snyk'
- script: |
    cd pip-sample && sudo snyk test
    displayName: 'snyk SCA'
    continueOnError: true

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
